export const ROUTES = {
  SIGNIN: '/signin',
  SIGNUP_AGREEMENT: '/signup/agreement',
  SIGNUP: '/signup',
  SIGNUP_SUCCESS: '/signup/success',
  HOME: '/',
  DETAIL: '/detail/:postId',
  SEARCH: '/search',
  STYLE: '/style',
  POST: '/post',
  MYPAGE: '/mypage',
  MODIFY: '/modify',
  EDIT: '/edit/:postId',
  ERROR_404: '/*',
};
